export const MODIFY_PRODUCT_NAME = "MODIFY_PRODUCT_NAME";
export const MODIFY_BRAND_NAME = "MODIFY_BRAND_NAME";
export const MODIFY_PRODUCT_DESCRIPTION = "MODIFY_PRODUCT_DESCRIPTION";
export const MODIFY_USUAL_RETAIL_PRICE = "MODIFY_USUAL_RETAIL_PRICE";
export const MODIFY_CURRENT_PRICE = "MODIFY_CURRENT_PRICE";
export const MODIFY_NUMBER_IN_STOCK = "MODIFY_NUMBER_IN_STOCK";
export const ADD_IMAGES_TO_FORM = "ADD_IMAGES_TO_FORM";
export const REMOVE_IMAGES_FROM_FORM = "REMOVE_IMAGES_FROM_FORM";
export const ADD_SPECIFICATIONS_TO_FORM = "ADD_SPECIFICATIONS_TO_FORM";
export const REMOVE_SPECIFICATIONS_FROM_FORM =
  "REMOVE_SPECIFICATIONS_FROM_FORM";
export const ADD_CATEGORY_TO_FORM = "ADD_CATEGORY_TO_FORM";
export const REMOVE_CATEGORY_FROM_FORM = "REMOVE_CATEGORY_FROM_FORM";
export const SET_PRODUCT_STATUS = "SET_PRODUCT_STATUS";
export const SET_SELLER_ID = "SET_SELLER_ID";
export const REMOVE_EXISTING_IMAGE_FROM_FORM_STATE =
  "REMOVE_EXISTING_IMAGE_FROM_FORM_STATE";
export const REMOVE_EXISTING_SPECIFICATION_FROM_FORM_STATE =
  "REMOVE_EXISTING_SPECIFICATION_FROM_FORM_STATE";
export const ADD_NEW_VARIATION_CATEGORY_TO_FORM_STATE =
  "ADD_NEW_VARIATION_CATEGORY_TO_FORM_STATE";
export const ADD_NEW_VARIATION_TO_FORM_STATE =
  "ADD_NEW_VARIATION_TO_FORM_STATE";
export const REMOVE_VARIATION_CATEGORY_FROM_FORM_STATE =
  "REMOVE_VARIATION_CATEGORY_FROM_FORM_STATE";
export const REMOVE_VARIATION_FROM_FORM_STATE =
  "REMOVE_VARIATION_FROM_FORM_STATE";
export const UPDATE_VARIATION_PRICE = "UPDATE_VARIATION_PRICE";
export const UPDATE_VARIATION_QUANTITY = "UPDATE_VARIATION_QUANTITY_COUNT";
